### ISSUE TITLE
Blinds open button is always grayed

### ISSUE THREAD

**Issue by glpotatoe** [andreasnuesslein/py-teleco-daisy#11]
Hi,

In home assistant, the blinds open button is always grayed, regardless of the position of the blinds : <img width="224" height="38" alt="Image" src="https://github.com/user-attachments/assets/f8b68126-0c71-4e36-8aab-f42f728e7904" />

Also, the position of the blinds is always at 100%, whether they are open, closed, or partially open (the value is correct in the Daisy app). Maybe the problem comes from there?

I can performe tests if needed.

Thank you again for the great work.

Edit : the blades have exactly the same issue.

**Comment by andreasnuesslein** [comment]
hi @glpotatoe 

are you sure you're using the newest version (>= 0.1.4) ? this is something i fixed a while back

**Comment by glpotatoe** [comment]
Yes, i was using 0.1.4 version.
I tried to update to 0.1.5, and i have an error loading the integration :

```
Enregistreur: homeassistant.setup
Source: setup.py:343
S'est produit pour la première fois: 15:17:32 (1 occurrence)
Dernier enregistrement: 15:17:32

Setup failed for custom integration 'teleco_daisy': Unable to import component: cannot import name 'DaisyHeater4CH' from 'teleco_daisy' (/usr/local/lib/python3.13/site-packages/teleco_daisy/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1003, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/teleco_daisy/__init__.py", line 7, in <module>
    from .hub import DaisyHub
  File "/config/custom_components/teleco_daisy/hub.py", line 4, in <module>
    from teleco_daisy import (
    ...<6 lines>...
    )
ImportError: cannot import name 'DaisyHeater4CH' from 'teleco_daisy' (/usr/local/lib/python3.13/site-packages/teleco_daisy/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/teleco_daisy/__init__.py", line 7, in <module>
    from .hub import DaisyHub
  File "/config/custom_components/teleco_daisy/hub.py", line 4, in <module>
    from teleco_daisy import (
    ...<6 lines>...
    )
ImportError: cannot import name 'DaisyHeater4CH' from 'teleco_daisy' (/usr/local/lib/python3.13/site-packages/teleco_daisy/__init__.py)
```

I just reverted back to 0.1.4 version, still have the issue.

**Comment by andreasnuesslein** [comment]
ffs, i keep forgetting the manifest.json.

just uploaded 0.1.6 now, please try that

**Comment by glpotatoe** [comment]
Just tried by copying the file directly in the custom component folder, same issue.

**Comment by andreasnuesslein** [comment]
okay, i did find another bug. 

however: can you send me a picture of the actual model you have there. and tell me the capabilities you're expecting?

based on your payload from #12  the device does not really support "levels", right?

**Comment by glpotatoe** [comment]
There are three possible statuses in the official application:

- Blind open, displaying at 100%:
![Image](https://github.com/user-attachments/assets/677f3990-a2f8-4efe-8ea6-6b8508900c53)

- Blind partially open (between 1 and 99%, I imagine), displaying without percentage:
![Image](https://github.com/user-attachments/assets/8b764685-3d57-4fd9-84bc-7ba759a91d89)

- Blind closed, displaying at 0%:
![Image](https://github.com/user-attachments/assets/6a7502e0-abcd-40c9-883a-3c2b9d1221b8)

Indeed, the precise position is not supported.
Does this answer your questions?

**Comment by andreasnuesslein** [comment]
try the new version v0.1.8

[![Open your Home Assistant instance and open a repository inside the Home Assistant Community Store.](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?owner=andreasnuesslein&repository=hass_teleco_daisy&category=integration)

**Comment by glpotatoe** [comment]
After the update, the blinds are no longer supported, with the message "This entity is no longer provided by the teleco_daisy integration. If the entity is no longer used, please delete it from the settings."

<img width="436" height="517" alt="Image" src="https://github.com/user-attachments/assets/66bafea6-8c9d-439e-ae00-7e41dabd1ccb" />

Entities disappeared even after rolling back to 0.1.4, and after completely reinstalling the HACS module. I just switched back to 0.1.8 from scratch, same problem.

**Comment by andreasnuesslein** [comment]
yeah it should be a new kind of entity - it's "shades" now.
can you see it there:

https://my.home-assistant.io/redirect/integration/?domain=teleco_daisy  ?

[![Open your Home Assistant instance and show an integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=teleco_daisy)

**Comment by glpotatoe** [comment]
The entities no longer appear, even after reloading:

<img width="766" height="295" alt="Image" src="https://github.com/user-attachments/assets/ea7552f1-0ed9-446f-85ff-9eb1f93664df" />

**Comment by andreasnuesslein** [comment]
yeah ... let's not talk about this anymore 🙈   *cough cough* ... try v0.1.9 please

**Comment by glpotatoe** [comment]
It's good, the entities are available again, well done:

<img width="767" height="457" alt="Image" src="https://github.com/user-attachments/assets/a83bf4a0-1d3e-4fb9-83c3-5acb42c5b949" />

From now on, I no longer have sliders, but only three buttons 'up', 'stop', and 'down', which corresponds well to the functions of the official application:

<img width="128" height="341" alt="Image" src="https://github.com/user-attachments/assets/e69e669e-8c5c-422c-a0cb-0e37985a32b4" />

It's starting to be pretty good :)

However, the up button remains grayed out, regardless of the position of the blind.

The blades always have the slider available in the interface, however, I only have access to 'open', 'stop', and 'close' in the official application.

<img width="141" height="389" alt="Image" src="https://github.com/user-attachments/assets/362a95d5-372a-406b-ada8-1356d6526a42" />

And the same problem as for the blinds, the 'open' button remains grayed out, regardless of the position of the blades.

**Comment by andreasnuesslein** [comment]
the problem behind this is that the API response for your blinds are apparently different to mine. so the correct state is not reflected.




can you re-run the `discover.py` like you did in #12 but when the shades are some different values.

in your response they both have:
```
  {'idInstallationDeviceStatusitem': 98822, 'idDevicetypeStatusitemModel': 32, 'statusitemCode': 'OPEN_CLOSE', 'statusItem': 'OPEN_CLOSE', 'statusValue': 'OPEN', 'lowlevelStatusitem': 'OPEN_CLOSE=OPEN'}
  {'idInstallationDeviceStatusitem': 98823, 'idDevicetypeStatusitemModel': 70, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '100', 'lowlevelStatusitem': 'LEVEL=100'}
```

set them (With the daisy app) to some different values. different heights, also closed and show me the outputs then.

**Comment by glpotatoe** [comment]
Blades open:
```
  {'idInstallationDeviceStatusitem': 98816, 'idDevicetypeStatusitemModel': 41, 'statusitemCode': 'OPEN_CLOSE', 'statusItem': 'OPEN_CLOSE', 'statusValue': 'OPEN', 'lowlevelStatusitem': 'OPEN_CLOSE=OPEN'}
  {'idInstallationDeviceStatusitem': 98817, 'idDevicetypeStatusitemModel': 72, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '100', 'lowlevelStatusitem': 'LEVEL=100'}
```

Blinds open:
```
  {'idInstallationDeviceStatusitem': 98820, 'idDevicetypeStatusitemModel': 32, 'statusitemCode': 'OPEN_CLOSE', 'statusItem': 'OPEN_CLOSE', 'statusValue': 'OPEN', 'lowlevelStatusitem': 'OPEN_CLOSE=OPEN'}
  {'idInstallationDeviceStatusitem': 98821, 'idDevicetypeStatusitemModel': 70, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '100', 'lowlevelStatusitem': 'LEVEL=100'}
```

LED 100% on (level 4 out of 4):
```
  {'idInstallationDeviceStatusitem': 98818, 'idDevicetypeStatusitemModel': 20, 'statusitemCode': 'POWER', 'statusItem': 'POWER', 'statusValue': 'ON', 'lowlevelStatusitem': None}
  {'idInstallationDeviceStatusitem': 98819, 'idDevicetypeStatusitemModel': 21, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '100', 'lowlevelStatusitem': None}
```

Partially open blades:
```
  {'idInstallationDeviceStatusitem': 98816, 'idDevicetypeStatusitemModel': 41, 'statusitemCode': 'OPEN_CLOSE', 'statusItem': 'OPEN_CLOSE', 'statusValue': 'STOP', 'lowlevelStatusitem': ''}
  {'idInstallationDeviceStatusitem': 98817, 'idDevicetypeStatusitemModel': 72, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '100', 'lowlevelStatusitem': None}
```

Partially open blinds:
```
  {'idInstallationDeviceStatusitem': 98820, 'idDevicetypeStatusitemModel': 32, 'statusitemCode': 'OPEN_CLOSE', 'statusItem': 'OPEN_CLOSE', 'statusValue': 'STOP', 'lowlevelStatusitem': ''}
  {'idInstallationDeviceStatusitem': 98821, 'idDevicetypeStatusitemModel': 70, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '100', 'lowlevelStatusitem': None}
```

LED 25% on (level 1 out of 4):
```
  {'idInstallationDeviceStatusitem': 98818, 'idDevicetypeStatusitemModel': 20, 'statusitemCode': 'POWER', 'statusItem': 'POWER', 'statusValue': 'ON', 'lowlevelStatusitem': 'POWER=ON'}
  {'idInstallationDeviceStatusitem': 98819, 'idDevicetypeStatusitemModel': 21, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '25', 'lowlevelStatusitem': 'LEVEL=25'}
```

Blades close:
```
  {'idInstallationDeviceStatusitem': 98816, 'idDevicetypeStatusitemModel': 41, 'statusitemCode': 'OPEN_CLOSE', 'statusItem': 'OPEN_CLOSE', 'statusValue': 'CLOSE', 'lowlevelStatusitem': ''}
  {'idInstallationDeviceStatusitem': 98817, 'idDevicetypeStatusitemModel': 72, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '100', 'lowlevelStatusitem': None}
```

Blinds close:
```
  {'idInstallationDeviceStatusitem': 98820, 'idDevicetypeStatusitemModel': 32, 'statusitemCode': 'OPEN_CLOSE', 'statusItem': 'OPEN_CLOSE', 'statusValue': 'CLOSE', 'lowlevelStatusitem': ''}
  {'idInstallationDeviceStatusitem': 98821, 'idDevicetypeStatusitemModel': 70, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '100', 'lowlevelStatusitem': None}
```

LED 0% on (level 0 out of 4):
```
  {'idInstallationDeviceStatusitem': 98818, 'idDevicetypeStatusitemModel': 20, 'statusitemCode': 'POWER', 'statusItem': 'POWER', 'statusValue': 'OFF', 'lowlevelStatusitem': None}
  {'idInstallationDeviceStatusitem': 98819, 'idDevicetypeStatusitemModel': 21, 'statusitemCode': 'LEVEL', 'statusItem': 'LEVEL', 'statusValue': '0', 'lowlevelStatusitem': None}
```

**Comment by andreasnuesslein** [comment]
okay so the (f***cking) API is always reporting "100%" back, as you can see.

try to change the code in the cover.py (in the hass-package):
```diff
    @property
    def current_cover_position(self) -> int | None:
-        return self._cover.position
+        return None

    @property
    def current_cover_tilt_position(self) -> int | None:
-        return self._cover.position
+        return None
```

**Comment by andreasnuesslein** [comment]
check newest release @glpotatoe

**Comment by glpotatoe** [comment]
The blades and blinds entities are now grayed out and unavailable :

<img width="131" height="33" alt="Image" src="https://github.com/user-attachments/assets/45b36249-92d4-4006-a44f-b613f70a4212" />

<img width="443" height="139" alt="Image" src="https://github.com/user-attachments/assets/6c35d03b-20da-4725-8750-ccf4cc5d24ce" />

Even after fully recharging the integration.
Like the other issue, I can test some things locally if needed or if it's simplier.

**Comment by andreasnuesslein** [comment]
@glpotatoe did you double check https://my.home-assistant.io/redirect/integration/?domain=teleco_daisy ?

**Comment by glpotatoe** [comment]
Yes, I just checked, same result. HA has restarted since, and I just reloaded the integration without success.

**Comment by andreasnuesslein** [comment]
@glpotatoe I think we fixed it

**Comment by glpotatoe** [comment]
Yes it's fixed and works great ! Thanks a lot !
